### ISSUE TITLE
RBC1GP Pause Menu text not translated

### ISSUE THREAD

**Issue by BudgetToaster** [igorciz777/RBC1GP-Translation-Pipeline#1]
I applied the translation patch, using release v0.3.1 of the RBC1GP translation patch, and for some reason, the pause menu text isn't translated on my end.

Screenshots:

![Racing Battle - C1 Grand Prix_SLPM-65897_20240816133016](https://github.com/user-attachments/assets/732e5106-27a1-4928-afce-7e48edcace62)
![Racing Battle - C1 Grand Prix_SLPM-65897_20240816133018](https://github.com/user-attachments/assets/11ddab71-a231-4943-bf09-f78e7b2205d4)
![Racing Battle - C1 Grand Prix_SLPM-65897_20240816133021](https://github.com/user-attachments/assets/aad2fcb2-3c55-46fe-98bd-5025e1f2f0d1)
![Racing Battle - C1 Grand Prix_SLPM-65897_20240816133024](https://github.com/user-attachments/assets/ec63f19e-b803-4e30-aaf7-16567a301eb2)
![Racing Battle - C1 Grand Prix_SLPM-65897_20240816133026](https://github.com/user-attachments/assets/2003ee45-1873-4098-8cec-863e42535c56)
![Racing Battle - C1 Grand Prix_SLPM-65897_20240816133029](https://github.com/user-attachments/assets/d8c009da-1afd-415e-bcdd-e2e11c9abe41)

I'm using the widescreen 16:9 patch alongside the translation patch, and I followed the steps that were in this video: https://www.youtube.com/watch?v=737ypvuaUAo

**Comment by igorciz777** [comment]
By v0.3.1 im guessing you mean GUT Archive Tools, as the translations get numerated by simple one digit, release 4 being the newest

Those installation steps show in my first video are outdated, especially when running the game on PCSX2
My bad for keeping them in there, i will cut it out from the vid

Read the README file that comes with the translation patch release instead and try again

**Comment by BudgetToaster** [comment]
ah shoot, seems i forgot about the .pnach file, my apologies on that

**Comment by BudgetToaster** [comment]
alright, using the pnach fixed the issue, thank you.
