### ISSUE TITLE
Tires type S translation

### ISSUE THREAD

**Issue by funwithbuns** [igorciz777/RBC1GP-Translation-Pipeline#5]
**Specify the fragment of the text**
Write down the fragment of the text that is mistranslated.

**Location**
Steps to find the text:
1. Go to the tuning shop and highlight TYPE S(H)

**Screenshots**
![Untitled](https://github.com/user-attachments/assets/45331a40-c598-42e2-bb57-0b7842c5dbdd)

**Correct translation**
They have better grip compared to HG tires. but have worse durability.

**Additional context**
simple typo

**Comment by igorciz777** [comment]
thanks, fixed in this [commit](https://github.com/igorciz777/RBC1GP-Translation-Pipeline/commit/b0e3e50ab04f622f777b4d3c23921df84f87818e)

will be available in the next release
